services:
    eliza:
        platform: linux/amd64
        command: ["pnpm", "start"]
        image: eliza-starter:v1
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        ports:
            - "3000:3000"
        restart: always
